### ISSUE TITLE
Don't call the main class SoapClient

### ISSUE THREAD

**Issue by willybarro** [Kanui/fcontrol#1]
I know it's a deep modification, but I don't think it makes sense to call the main class "SoapClient".
SoapClient is a "reserved" class name and the underlying implemented protocol name shouldn't be exposed as the main entry point on the general API.
Calling it \FControl\FControl or \FControl\Client would make more sense.

**Comment by tonicospinelli** [comment]
You are right, man!! Thinking about it, I have a propose, what about `\FControl\RiskManager\`?
